Convert circleci workflows to github actions part 2.

diff --git a/.github/workflows/test-all.yml b/.github/workflows/test-all.yml
--- a/.github/workflows/test-all.yml
+++ b/.github/workflows/test-all.yml
@@ -676,3 +676,154 @@ jobs:
         with:
           name: rntester-apk
           path: packages/rn-tester/android/app/build/outputs/apk/
+  build_npm_package:
+    runs-on: ubuntu-latest
+    needs: [set_release_type, prepare_hermes_workspace, build_hermes_macos, build_hermesc_linux, build_hermesc_windows,build_andriod]
+    container:
+      image: reactnativecommunity/react-native-android:latest
+      env:
+        TERM: "dumb"
+        GRADLE_OPTS: '-Dorg.gradle.daemon=false'
+        # By default we only build ARM64 to save time/resources. For release/nightlies/prealpha, we override this value to build all archs.
+        ORG_GRADLE_PROJECT_reactNativeArchitectures: "arm64-v8a"
+        # Repeated here, as the environment key in this executor will overwrite the one in defaults
+        PUBLIC_ANALYSISBOT_GITHUB_TOKEN_A: ${{ secrets.GITHUB_ANALYSISBOT_TOKEN_A }}
+        PUBLIC_ANALYSISBOT_GITHUB_TOKEN_B: ${{ secrets.GITHUB_ANALYSISBOT_TOKEN_B }}
+        HERMES_WS_DIR: /tmp/hermes
+    steps:
+      - name: Add github.com to SSH known hosts
+        run: |
+          mkdir -p ~/.ssh
+          echo '|1|If6MU203eXTaaWL678YEfWkVMrw=|kqLeIAyTy8pzpj8x8Ae4Fr8Mtlc= ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==' >> ~/.ssh/known_hosts
+      - name: Checkout
+        uses: actions/checkout@v4.1.1
+      - name: Create /tmp/hermes/osx-bin directory
+        run: mkdir -p /tmp/hermes/osx-bin
+      - name: Download osx-bin release artifacts
+        uses: actions/download-artifact@v4.1.3
+        with:
+          name: hermes-osx-bin-Release
+          path: /tmp/hermes/osx-bin
+      - name: Download osx-bin debug artifacts
+        uses: actions/download-artifact@v4.1.3
+        with:
+          name: hermes-osx-bin-Debug
+          path: /tmp/hermes/osx-bin
+      - name: Download darwin-bin release artifacts
+        uses: actions/download-artifact@v4.1.3
+        with:
+          name: hermes-darwin-bin-Release
+          path: /tmp/hermes/hermes-runtime-darwin
+      - name: Download darwin-bin debug artifacts
+        uses: actions/download-artifact@v4.1.3
+        with:
+          name: hermes-darwin-bin-Debug
+          path: /tmp/hermes/hermes-runtime-darwin
+      - name: Download hermes dSYM debug artifacts
+        uses: actions/download-artifact@v4.1.3
+        with:
+          name: hermes-dSYM-Debug
+          path: /tmp/hermes/dSYM/Debug
+      - name: Download hermes dSYM release vartifacts
+        uses: actions/download-artifact@v4.1.3
+        with:
+          name: hermes-dSYM-Release
+          path: /tmp/hermes/dSYM/Release
+      - name: Download windows-bin artifacts
+        uses: actions/download-artifact@v4.1.3
+        with:
+          name: hermes-win64-bin
+          path: /tmp/hermes/win64-bin
+      - name: Download linux-bin artifacts
+        uses: actions/download-artifact@v4.1.3
+        with:
+          name: hermes-linux-bin
+          path: /tmp/hermes/linux64-bin
+      - name: Show /tmp/hermes directory
+        run: ls -lR /tmp/hermes
+      - name: Cache setup
+        id: cache_setup
+        uses: ./.github/actions/cache_setup
+        with:
+          hermes-version: ${{ needs.prepare_hermes_workspace.outputs.hermes-version }}
+          react-native-version: ${{ needs.prepare_hermes_workspace.outputs.react-native-version }}
+      - name: Copy Hermes binaries
+        shell: bash
+        run: |
+          mkdir -p ./packages/react-native/sdks/hermesc ./packages/react-native/sdks/hermesc/osx-bin ./packages/react-native/sdks/hermesc/win64-bin ./packages/react-native/sdks/hermesc/linux64-bin
+
+          # When build_hermes_macos runs as a matrix, it outputs
+          if [[ -d $HERMES_WS_DIR/osx-bin/Release ]]; then
+            cp -r $HERMES_WS_DIR/osx-bin/Release/* ./packages/react-native/sdks/hermesc/osx-bin/.
+          elif [[ -d $HERMES_WS_DIR/osx-bin/Debug ]]; then
+            cp -r $HERMES_WS_DIR/osx-bin/Debug/* ./packages/react-native/sdks/hermesc/osx-bin/.
+          else
+            ls $HERMES_WS_DIR/osx-bin || echo "hermesc macOS artifacts directory missing."
+            echo "Could not locate macOS hermesc binary."; exit 1;
+          fi
+
+          cp -r $HERMES_WS_DIR/win64-bin/* ./packages/react-native/sdks/hermesc/win64-bin/.
+          cp -r $HERMES_WS_DIR/linux64-bin/* ./packages/react-native/sdks/hermesc/linux64-bin/.
+          mkdir -p ./packages/react-native/ReactAndroid/external-artifacts/artifacts/
+          cp $HERMES_WS_DIR/hermes-runtime-darwin/hermes-ios-debug.tar.gz ./packages/react-native/ReactAndroid/external-artifacts/artifacts/hermes-ios-debug.tar.gz
+          cp $HERMES_WS_DIR/hermes-runtime-darwin/hermes-ios-release.tar.gz ./packages/react-native/ReactAndroid/external-artifacts/artifacts/hermes-ios-release.tar.gz
+          cp $HERMES_WS_DIR/dSYM/Debug/hermes.framework.dSYM  ./packages/react-native/ReactAndroid/external-artifacts/artifacts/hermes-framework-dSYM-debug.tar.gz
+          cp $HERMES_WS_DIR/dSYM/Release/hermes.framework.dSYM  ./packages/react-native/ReactAndroid/external-artifacts/artifacts/hermes-framework-dSYM-release.tar.gz
+      - name: Use Node.js 18
+        uses: actions/setup-node@v4.0.0
+        with:
+          node-version: 18
+          cache: 'yarn'
+      - name: Install dependencies
+        run: yarn install --non-interactive
+      - name: Build packages
+        run: yarn build
+      # Continue with publish steps
+      - name: Set npm credentials
+        if: needs.set_release_type.outputs.RELEASE_TYPE == 'release' ||
+            needs.set_release_type.outputs.RELEASE_TYPE == 'nightly'
+        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.CIRCLE_NPM_TOKEN }}" > ~/.npmrc
+      - name: Publish NPM
+        run: |
+          # We can't have a separate step because each command is executed in a separate shell
+          # so variables exported in a command are not visible in another.
+          if [[ ${{ needs.set_release_type.outputs.RELEASE_TYPE }} == "dry-run" ]]; then
+            export ORG_GRADLE_PROJECT_reactNativeArchitectures="arm64-v8a"
+          else
+            export ORG_GRADLE_PROJECT_reactNativeArchitectures="armeabi-v7a,arm64-v8a,x86,x86_64"
+          fi
+          node ./scripts/releases-ci/publish-npm.js -t ${{ needs.set_release_type.outputs.RELEASE_TYPE }}
+      - name: Zip Maven Artifacts from /tmp/maven-local
+        run: zip -r /tmp/maven-local.zip /tmp/maven-local
+      - name: Upload Maven Artifacts
+        uses: actions/upload-artifact@v4.3.1
+        with:
+          name: maven-local
+          path: /tmp/maven-local.zip
+      - name: Upload npm logs
+        uses: actions/upload-artifact@v4.3.1
+        with:
+          name: npm-logs
+          path: ~/.npm/_logs
+      - name: Build release package as a job artifact
+        if: needs.set_release_type.outputs.RELEASE_TYPE == 'dry=run'
+        run: |
+          mkdir -p build
+
+          FILENAME=$(cd packages/react-native; npm pack | tail -1)
+          mv packages/react-native/$FILENAME build/
+
+          echo $FILENAME > build/react-native-package-version
+      - name: Upload release package
+        uses: actions/upload-artifact@v4.3.1
+        if: needs.set_release_type.outputs.RELEASE_TYPE == 'dry-run'
+        with:
+          name: react-native-package
+          path: ~/react-native/build/
+      - name: Update rn-diff-purge to generate upgrade-support diff
+        if: needs.set_release_type.outputs.RELEASE_TYPE == 'release'
+        run: |
+          curl -X POST https://api.github.com/repos/react-native-community/rn-diff-purge/dispatches \
+            -H "Accept: application/vnd.github.v3+json" \
+            -H "Authorization: Bearer $REACT_NATIVE_BOT_GITHUB_TOKEN" \
+            -d "{\"event_type\": \"publish\", \"client_payload\": { \"version\": \"${{ github.ref_name }}\" }}"
