add matrix for macos

diff --git a/.github/workflows/test-all.yml b/.github/workflows/test-all.yml
--- a/.github/workflows/test-all.yml
+++ b/.github/workflows/test-all.yml
@@ -109,14 +109,8 @@ jobs:
         with:
           path: .git
           key: v1-checkout-checkout-${{ runner.arch }}-${{ github.ref }}-${{ github.sha }}
-
-      ## This above step needs to be put into it's own action, and it needs to set an output for the value of the react native version.  
       - name: Setup Hermes workspace
-        run: |
-          mkdir -p $HERMES_OSXBIN_ARTIFACTS_DIR ./packages/react-native/sdks/hermes
-          cp -r $HERMES_WS_DIR/hermes/* ./packages/react-native/sdks/hermes/.
-          cp -r ./packages/react-native/sdks/hermes-engine/utils ./packages/react-native/sdks/hermes/.
-
+        uses: ./.github/actions/setup-hermes-workspace
       - name: Hermes apple cache
         uses: actions/cache@v4.0.0
         with:
@@ -127,3 +121,83 @@ jobs:
           cd ./packages/react-native/sdks/hermes || exit 1
           . ./utils/build-apple-framework.sh
           build_host_hermesc_if_needed
+  build_apple_slices_hermes:
+    runs-on: macos-12
+    needs: [build_hermesc_apple, prepare_hermes_workspace]
+    env:
+      HERMES_WS_DIR: /tmp/hermes
+      HERMES_TARBALL_ARTIFACTS_DIR: /tmp/hermes/hermes-runtime-darwin
+      HERMES_OSXBIN_ARTIFACTS_DIR: /tmp/hermes/osx-bin
+    strategy:
+      matrix:
+        flavor: [Debug, Release]
+        slice: [macosx, iphoneos, iphonesimulator, catalyst]
+    steps:
+      - name: Cache hermes workspace
+        uses: actions/cache@v4.0.0
+        with:
+          path: /tmp/hermes
+          key: hermes
+      - name: Restore git cache
+        uses: actions/cache/restore@v4.0.0
+        with:
+          path: .git
+          key: v1-checkout-checkout-${{ runner.arch }}-${{ github.ref }}-${{ github.sha }}
+      - name: Checkout
+        uses: actions/checkout@v4.1.1
+      - name: Save git cache
+        uses: actions/cache/save@v4.0.0
+        with:
+          path: .git
+          key: v1-checkout-checkout-${{ runner.arch }}-${{ github.ref }}-${{ github.sha }}
+      - name: Setup Hermes workspace
+        uses: ./.github/actions/setup-hermes-workspace
+      - name: Hermes apple cache
+        uses: actions/cache@v4.0.0
+        with:
+          path: ./packages/react-native/sdks/hermes/build_host_hermesc
+          key: v2-hermesc-apple-${{ needs.prepare_hermes_workspace.outputs.hermes-version }}-${{ needs.prepare_hermes_workspace.outputs.react-native-version }}
+      - name: Slice cache
+        uses: actions/cache@v4.0.0
+        with:
+          path: ./packages/react-native/sdks/hermes/build_${{ matrix.slice }}_${{ matrix.flavor }}
+          key: v4-hermes-apple-${{ needs.prepare_hermes_workspace.outputs.hermes-version}}-${{ needs.prepare_hermes_workspace.outputs.react-native-version }}-${{ hashfiles('packages/react-native/sdks/hermes-engine/utils/build-apple-framework.sh') }}-${{ matrix.slice }}-${{ matrix.flavor }}
+      - name: Build the Hermes ${{ matrix.slice }} frameworks
+        run: |
+          cd ./packages/react-native/sdks/hermes || exit 1
+          SLICE=${{ matrix.slice }}
+          FLAVOR=${{ matrix.flavor }}
+          FINAL_PATH=build_"$SLICE"_"$FLAVOR"
+          echo "Final path for this slice is: $FINAL_PATH"
+
+          if [[ -d "$FINAL_PATH" ]]; then
+            echo "[HERMES] Skipping! Found the requested slice at $FINAL_PATH".
+            exit 0
+          fi
+
+          if [[ "$SLICE" == "macosx" ]]; then
+            echo "[HERMES] Building Hermes for MacOS"
+            BUILD_TYPE="${{ matrix.flavor }}" ./utils/build-mac-framework.sh
+          else
+            echo "[HERMES] Building Hermes for iOS: $SLICE"
+            BUILD_TYPE="${{ matrix.flavor }}" ./utils/build-ios-framework.sh "$SLICE"
+          fi
+
+          echo "Moving from build_$SLICE to $FINAL_PATH"
+          mv build_"$SLICE" "$FINAL_PATH"
+
+          # check whether everything is there
+          if [[ -d "$FINAL_PATH/API/hermes/hermes.framework" ]]; then
+            echo "Successfully built hermes.framework for $SLICE in $FLAVOR"
+          else
+            echo "Failed to built hermes.framework for $SLICE in $FLAVOR"
+            exit 1
+          fi
+
+          if [[ -d "$FINAL_PATH/API/hermes/hermes.framework.dSYM" ]]; then
+            echo "Successfully built hermes.framework.dSYM for $SLICE in $FLAVOR"
+          else
+            echo "Failed to built hermes.framework.dSYM for $SLICE in $FLAVOR"
+            echo "Please try again"
+            exit 1
+          fi
