build windows

diff --git a/.github/workflows/test-all.yml b/.github/workflows/test-all.yml
--- a/.github/workflows/test-all.yml
+++ b/.github/workflows/test-all.yml
@@ -463,4 +463,80 @@ jobs:
         with:
           name: linux-artifacts
           path: /tmp/hermes/linux64-bin
-    
+  build_hermesc_windows:
+    runs-on: windows-latest
+    needs: prepare_hermes_workspace
+    env:
+      HERMES_WS_DIR: 'C:\tmp\hermes'
+      ICU_URL: "https://github.com/unicode-org/icu/releases/download/release-64-2/icu4c-64_2-Win64-MSVC2017.zip"
+      MSBUILD_DIR: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin'
+      CMAKE_DIR: 'C:\Program Files\CMake\bin'
+    steps:
+      - name: Restore git cache
+        uses: actions/cache/restore@v4.0.0
+        with:
+          path: .git
+          key: v1-checkout-checkout-${{ runner.arch }}-${{ github.ref }}-${{ github.sha }}
+      - name: Checkout
+        uses: actions/checkout@v4.1.1
+      - name: Cache setup
+        id: cache_setup
+        uses: ./.github/actions/cache_setup
+      - name: Windows cache
+        uses: actions/cache@v4.0.0
+        with:
+          key: v2-hermes-${{ github.job }}-windows-${{ needs.prepare_hermes_workspace.outputs.hermes-version }}-${{ needs.prepare_hermes_workspace.outputs.react-native-version }}
+          path: |
+            C:\tmp\hermes\win64-bin\
+            C:\tmp\hermes\hermes\icu\
+            C:\tmp\hermes\hermes\deps\
+            C:\tmp\hermes\hermes\build_release\
+      - name: Set up workspace
+        run: |
+          New-Item -ItemType Directory $Env:HERMES_WS_DIR
+          New-Item -ItemType Directory $Env:HERMES_WS_DIR\icu
+          New-Item -ItemType Directory $Env:HERMES_WS_DIR\deps
+          New-Item -ItemType Directory $Env:HERMES_WS_DIR\win64-bin
+          New-Item -ItemType SymbolicLink -Target tmp\hermes\hermes -Path $Env:HERMES_WS_DIR -Name hermes
+      - name: Build HermesC for Windows
+        run: |
+          if (-not(Test-Path -Path $Env:HERMES_WS_DIR\win64-bin\hermesc.exe)) {
+            choco install --no-progress cmake --version 3.14.7
+            if (-not $?) { throw "Failed to install CMake" }
+
+            cd $Env:HERMES_WS_DIR\icu
+            # If Invoke-WebRequest shows a progress bar, it will fail with
+            #   Win32 internal error "Access is denied" 0x5 occurred [...]
+            $progressPreference = 'silentlyContinue'
+            Invoke-WebRequest -Uri "$Env:ICU_URL" -OutFile "icu.zip"
+            Expand-Archive -Path "icu.zip" -DestinationPath "."
+
+            cd $Env:HERMES_WS_DIR
+            Copy-Item -Path "icu\bin64\icu*.dll" -Destination "deps"
+            # Include MSVC++ 2015 redistributables
+            Copy-Item -Path "c:\windows\system32\msvcp140.dll" -Destination "deps"
+            Copy-Item -Path "c:\windows\system32\vcruntime140.dll" -Destination "deps"
+            Copy-Item -Path "c:\windows\system32\vcruntime140_1.dll" -Destination "deps"
+
+            $Env:PATH += ";$Env:CMAKE_DIR;$Env:MSBUILD_DIR"
+            $Env:ICU_ROOT = "$Env:HERMES_WS_DIR\icu"
+
+            cmake -S hermes -B build_release -G 'Visual Studio 16 2019' -Ax64 -DCMAKE_BUILD_TYPE=Release -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=True -DHERMES_ENABLE_WIN10_ICU_FALLBACK=OFF
+            if (-not $?) { throw "Failed to configure Hermes" }
+            cd build_release
+            cmake --build . --target hermesc --config Release
+            if (-not $?) { throw "Failed to build Hermes" }
+
+            cd $Env:HERMES_WS_DIR
+            Copy-Item -Path "build_release\bin\Release\hermesc.exe" -Destination "win64-bin"
+            # Include Windows runtime dependencies
+            Copy-Item -Path "deps\*" -Destination "win64-bin"
+          }
+          else {
+              Write-Host "Skipping; Clean c:\tmp\hermes\win64-bin to rebuild."
+          }
+      - name: Upload windows artifacts
+        uses: actions/upload-artifact@v4.3.0
+        with:
+          name: windows-artifacts
+          path: C:\tmp\hermes\win64-bin\
